/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_mim_cl_server_services_JniDirectionService */

#ifndef _Included_fr_mim_cl_server_services_JniDirectionService
#define _Included_fr_mim_cl_server_services_JniDirectionService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_mim_cl_server_services_JniDirectionService
 * Method:    getShortestPath
 * Signature: (JJ)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_fr_mim_cl_server_services_JniDirectionService_getShortestPath
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     fr_mim_cl_server_services_JniDirectionService
 * Method:    getTravelingSalesMan
 * Signature: (Ljava/util/Set;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_fr_mim_cl_server_services_JniDirectionService_getTravelingSalesMan
  (JNIEnv *, jobject, jobject);

/*
 * Class:     fr_mim_cl_server_services_JniDirectionService
 * Method:    getNearestPoint
 * Signature: (DD)Lfr/mim/cl/server/model/Place;
 */
JNIEXPORT jobject JNICALL Java_fr_mim_cl_server_services_JniDirectionService_getNearestPoint
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
